### ISSUE TITLE
Add a section about preferred tools

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1027]
Talk about VSCode, Vetur extension, terminal interfaces and other productivity tools we use in the team.

**Comment by techtolentino** [comment]
@delapuente - just for clarification, when we say _Add a section_, I'm assuming we mean to the project wiki?

**Comment by delapuente** [comment]
Yes, or the CONTRIBUTING.md. It means to add to documentation, whenever it resides.

**Comment by techtolentino** [comment]
@pandasa123 for now, I think what we have document is adequate enough to promote dev consistency.

The dev team did have a recent meeting where we discussed other productivity tools, VS Code extensions, and ways of working, but I don't since each developer creates their own productivity-environment, I'm not sure it's worth documenting. 

I say let's close this and if the need ever arises, we'll revisit.
