### ISSUE TITLE
homepage Start locally toggle

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#1219]
### Steps to reproduce the problem
- Navigate to qiskit.org > Quick Start section > Start locally
- select `Unstable`
- see the part that says _'Building Qiskit requires a C++ compiler and development headers'_

### What is the current behavior?
The copy is within a accordion/toggle component

### What is the expected behavior?
Maybe this copy should stand on its own? Unless there really needs to be a toggling experience?

![Screen Shot 2020-12-04 at 7 02 32 AM](https://user-images.githubusercontent.com/6276074/101187199-4da5fd80-3611-11eb-9af1-dc86b8d9ca48.png)

**Comment by delapuente** [comment]
This is not malfunctioning. The toggling experience is intended. Check with @JRussellHuffman for more information on this.

**Comment by eddybrando** [comment]
I believe the expected behaviour after clicking on the accordion header is to have some section(s) of content toggle. In this particular case we're missing that extra content:

![ezgif-6-6beae3642267](https://user-images.githubusercontent.com/22047320/102200405-195df700-3ec5-11eb-98a8-df577256257f.gif)

After inspecting the code I realised that the extra content section corresponds to a component displaying the prerequisites, which currently is not being registered correctly:

<img width="514" alt="Screenshot 2020-12-15 at 11 12 14" src="https://user-images.githubusercontent.com/22047320/102201432-655d6b80-3ec6-11eb-88e0-28401716e572.png">

<img width="623" alt="Screenshot 2020-12-15 at 11 11 40" src="https://user-images.githubusercontent.com/22047320/102201394-54145f00-3ec6-11eb-9baf-b34e951caa99.png">

**Comment by JRussellHuffman** [comment]
Checking on this, it looks like toggle experience is working as intended, but the content isn't rendering?
