### ISSUE TITLE
Research Sphinx theme customization vs extracting menu component

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1331]

**Comment by eddybrando** [comment]
This are the results of my research regarding the customisation of the Sphinx theme in order to improve the UI consistency across all of qiskit.org, with the Header / Menu component being the main focus.

### Motivation

We want to have a consistent UI across qiskit.org, and this includes the documentation pages.

The challenge is that since the documentation pages aren’t part of the [Nuxt project](https://github.com/Qiskit/qiskit.org), they don’t have access to the Vue.js UI components we’re developing there, like the Header / Menu.

The goal is to find a way of syncing the UI shell elements, like the header and footer.

### Where to apply the Sphinx theme changes

The Sphinx theme used for the Qiskit documentation is custom made and lives in the repository https://github.com/Qiskit/qiskit_sphinx_theme, to which I now have push access.

This will be helpful to test and apply some of the changes needed to work towards the aforementioned UI consistency.

### Approach 1: Mirroring

The quickest method would be to replicate the base shell elements (starting with the Header / Menu) from the [Nuxt project](https://github.com/Qiskit/qiskit.org) into the the [Sphinx theme project](https://github.com/Qiskit/qiskit_sphinx_theme).

The Sphinx theme is also just HTML, CSS and JavaScript with some syntactic sugar for Sphinx, so we should be able to choose a _vanilla JS_ or Vue.js approach as we see fit.

The drawback with this method is the fact that we’re creating new code for the same component, which duplicates the code maintenance efforts for future changes.

This should be seen as a way to get the quick win of having a more consistent UI soon, but we should consider a more future-proof approach for the near future.

### Approach 2: Reusing UI components

We can use Vue.js components in the Sphinx documentation theme, since the theme is HTML, CSS and JavaScript with some syntactic sugar.

After research and some internal discussions, we believe that a good approach would be to create a UI components library with Vue.js components and CSS / Sass that can be consumed by the Qiskit Nuxt project, the Sphinx documentation theme and any other Qiskit projects that could profit from sharing the design language and UI components from qiskit.org.

I’ve already started testing some approaches. The main goal is to make the components as easily consumable and maintainable as possible, so we’ll look deeper into using Vue 3 instead of Vue 2, and setting up testing, Storybook and linting from the get-go.

I’ve created a [repository for this library](https://github.com/qiskit-community/qiskit-vue), as well as a [NPM package](https://www.npmjs.com/package/@qiskit-community/qiskit-vue). Both are still in a _work in progress_ state.
