### ISSUE TITLE
Add Github button and Install section for Aqua GUI

### ISSUE THREAD

**Issue by hushaohan** [Qiskit/qiskit.org#144]
As Aqua's GUI has been extracted out as a separate repo/package, the GUI section of the Aqua page likely needs the following two elements:

- A Github button pointing to `https://github.com/Qiskit/qiskit-aqua-interfaces`

- An `Install` section for `pip install qiskit-aqua-interfaces`

**Comment by carlosazaustre** [comment]
Thanks for letting know @hushaohan 
I think @derivation is working in a way to properly show all the specs from Aqua. I don't know if it is related to that?

**Comment by lerongil** [comment]
@hushaohan Is this for qiskit.org or the documentation?

**Comment by hushaohan** [comment]
> @hushaohan Is this for qiskit.org or the documentation?

This is for the page https://qiskit.org/aqua

**Comment by derivation** [comment]
@carlosazaustre Yes, I'd say that this is related. However, the plans you and I discussed were for less time sensitive materials. This issue is more time sensitive.

@pistoia @lerongil 
How should we position the GUI (this is really an anachronism now, supplanted by the word "app")? The positioning informs how to present the Aqua App on qiskit.org. I think there are only two options:

1. The Aqua App is a built-in add-on to Aqua, the library.
2. The Aqua App is a product, separate from but dependent upon Aqua, the library.

Here are examples of these two approaches:

1. The [Signal Processing Toolbox](https://www.mathworks.com/products/signal.html) has a code interface and an app interface. Just below the fold on that page is a section on Capabilities. The first capability is Signal Exploration, which leads to a [page highlighting the app](https://www.mathworks.com/products/signal/features.html#signal-exploration).
2. [GitHub Desktop](https://desktop.github.com/) is a product, separate from but dependent on the git code interface.

**Comment by jwoehr** [comment]
Just got stung by this and had to ask a lazy question on qiskit.slack.org, "qiskit_aqua_ui ... can't find this command. Can't find any module in aqua like that .."

**Comment by woodsp-ibm** [comment]
Can we get the Aqua web page updated with this relatively small change at least in the interim as per the request. The command line tools and UI application were moved out into this separate package at the last release and there is no indication this on the main Aqua page. We are getting questions as per above on where this is etc. since they are no longer installed when installing aqua.

**Comment by lerongil** [comment]
@hushaohan Is the below image something you are looking for? With the Github button pointing to: https://github.com/Qiskit/qiskit-aqua-interfaces. Does the text need to be updated as well? We should add the Github button below the text for consistency but added it next to `GUI` for demonstration. 

![image](https://user-images.githubusercontent.com/9096989/59774545-9e8b3000-927d-11e9-99ff-500913d094e7.png)

**Comment by hushaohan** [comment]
@lerongil yea something like that. as to the exact style, i have no problem either way.

btw the new `Install` section

```
[python3] $ pip install qiskit-aqua-interfaces
```

is to be added in addition to, not to replace, the current invocation section

```
[python3] $ qiskit_aqua_ui
[python3] $ qiskit_chemistry_ui
```
