### ISSUE TITLE
Investigate Verification and CMS for Benchmarks

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1709]
1. Can we re-use part of the challenge platform for verification? 
2. Can we reproduce the same contribution model + content management in a CMS vs Github? Tradeoffs if we move over.
3. Nice to have: how can we use the CMS across projects?

**Comment by eddybrando** [comment]
### 1. Potentially reusable from Challenges / Quantum Lab

- The grading server could be reused for the first validation step of submissions if these are in the Qiskit or OpenQASM format.
- The challenges content management flow for exercises and validations cannot be reused since it requires a dedicated team that know the "complex" process and invests time in learning this flow because they'll use it multiple times, which is not always going to be the case for the benchmarks platform contributors.

### 2. Contribution model & content management in CMSes vs GitHub PRs

- CMSes with good Nuxt integration: Strapi, Storyblok, Contentful, Forestry
- Problem with these CMSes: Limited number of collaborators / seats / members. We need many users to be able to submit problems & solutions.
- The GitHub PRs flow is complex and not so simple (for the benchmarks users). It may constitute a barrier that deters users from contributing to the project.
- Submission forms and database in own server may be a better solution for our specific case.

### 3. Reusability of CMS flow in other projects

- The projects (Challenges / Qiskit.org / Benchmarks) have different needs for content management:
  - Challenges: CMS to organise exercises validations
  - Qiskit.org: CMS to allow for individual pages' copy editing by a defined set of people
  - Benchmarks: CMS open for guest submissions for problems and solutions (including file uploads)
- The flows for contribution and validation, as well the content types and structures are different, thus reusing CMS solutions seems not worthy.
