### ISSUE TITLE
Explore instrumentalizing the word searches in the megamenu

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1857]

**Comment by eddybrando** [comment]
### What questions do we want to answer?

1. What search terms are being used the most in the mega menu?
2. What search terms lead to a link click?
3. Which textbook visits are the result of a search in the mega menu?
4. What search terms do not lead to a link click?

### What should we track?

In order to solve these questions, we need to track:

1. The referrer / the element that emits the tracked event (the _mega menu dropdown search input field thingy_)
2. The search term
3. The link target, in the case of a link click

### Tracking with URL parameters

In web analytics, the `ref` URL parameter appears to be a de facto standard for referrers tracking. The same goes for the `q` parameter for search terms tracking.

Amplitude appears to have some "automatic tracking" support for `ref` (https://developers.amplitude.com/docs/javascript#track-referrers), but I wasn't able to confirm what this means since I currently don't have access to the Amplitude dashboard.

There is no mention of the `q` parameter in the Amplitude documentation that I could find. But if it works similarly to the Google Analytics dashboard, we may be able to create a filter to get the search term data for the events containing the _mega menu dropdown_ referrer, and so be able to answer our analytics questions.

The URLs that we would get would be in a syntax similar to this: `<origin + path>/?<referrer>&<search term>`

**Example:** `https://qiskit.org/course/foo-course/?ref=textbook-mega-menu&q=foo`

In this example, "textbook-mega-menu" identifies the _mega menu dropdown, where the user searched for "foo", which resulted in a visit to `https://qiskit.org/course/foo-course/`.

### Tracking of search terms that do not lead to link clicks

Searches that do not result in link clicks won't be tracked with the aforementioned approach. Nevertheless, these might contain valuable information in terms of UX optimisation, that may lead us to rename links, create synonyms, etc.

In order to track these search terms, we may emit tracking events via JS after the user stops writing a search term.

This might be achieved with a timeout function that delays emitting the tracking event for about 300 ms, and cancels every other event within said timeframe.

**Comment by eddybrando** [comment]
### Update regarding tracking with URL parameters

Some of the links in the _Textbook mega menu_ point to URLs that respond with a 302 redirect (Mathigon's implementation).

**Example:** `https://platypus.qiskit.org/course/ch-prerequisites?ref=foo` redirects to `https://platypus.qiskit.org/course/ch-prerequisites/environment-setup-guide-to-work-with-qiskit-textbook`

Since this implementation is being done server-side via an HTTP response, and since the implementation comes from Mathigon itself, Amplitude won't be able to track neither the referrer nor the search term, because those parameters are not passed to the redirection target URL.

This renders the approach about tracking the searches with URL parameters obsolete for this scenario.

We need to emit tracking events with the search information similarly to how it's being done in the link / CTA components.
