### ISSUE TITLE
As a textbook user, I want to be able to access the new qiskit textbook beta, so that I can try all the new available featuers.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#1925]
Acceptance criteria
- [x] Add a banner to every page of the current qiskit textbook, linking to the qiskit textbook beta home page. Design ~~[here](https://www.figma.com/file/U18nAt8unUeWqpByzpmd33/1914-beta-launch?node-id=4%3A349)~~ [here](https://www.figma.com/file/U18nAt8unUeWqpByzpmd33/1914-beta-launch?node-id=4%3A350) #1926 
- [x] replace the "sign up for beta testing" link in the right side panel of the current textbook with a link to the new textbook. Design [here](https://www.figma.com/file/U18nAt8unUeWqpByzpmd33/1914-beta-launch?node-id=4%3A350). The text should read "Try the new textbook beta". #1927 .

**Comment by techtolentino** [comment]
@JRussellHuffman - quick question: does the main banner persist on all pages, or just the home?

**Comment by techtolentino** [comment]
@JRussellHuffman - we'll need to update the main banner copy to reflect that this is _beta_ - open to discuss

**Comment by JRussellHuffman** [comment]
Yes, sounds good. Let's discuss.

**Comment by techtolentino** [comment]
@vabarbosa and @JRussellHuffman will discuss

**Comment by vabarbosa** [comment]
@JRussellHuffman yes, it is possible to include the banner in all pages (without having to update every notebook)

**Comment by JRussellHuffman** [comment]
@vabarbosa great, then I think that is the way we should go. I updated the (design file)[https://www.figma.com/file/U18nAt8unUeWqpByzpmd33/1914-beta-launch?node-id=4%3A350]. 
@techtolentino I took a pass at updating the copy to include "beta". Let me know what you think about it.

**Comment by vabarbosa** [comment]
@JRussellHuffman it is not mentioned here if the banner should be sticky or not? the reason i ask is because for [the others pages it is stated the banner is not sticky](https://github.com/Qiskit/qiskit.org/issues/1914) so i would assume this is also not sticky. however the textbook is basically 3 columns (left sidebar, main content,  right sidebar) each scrolling independently:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/13156555/124226364-f993c680-dad6-11eb-9768-d69b66b38cfb.png">

if it is sticky i have no question 

...but if it is not sticky, then with which column should the banner scroll? i would assume it would be with the center/main content column. and if this is the case, should the banner perhaps be contained within the center/main content column (similar to what is designed for the beta pages)?

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/13156555/124227179-3ca26980-dad8-11eb-8d11-e7c14913a334.png">

let me know if what i am trying to say makes sense and what your recommendation is. thanks.

**Comment by JRussellHuffman** [comment]
You are right that it should not be sticky. And I agree that having it scroll with the center/main content makes the most sense.

**Comment by vabarbosa** [comment]
these changes are in place in current textbook and just waiting go live date to merge
- https://github.com/qiskit-community/qiskit-textbook/pull/1193
- https://github.com/qiskit-community/qiskit-textbook/pull/1195
