### ISSUE TITLE
Update "Sign up for beta testing" link in old textbook

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1927]
Related to #1925

**Comment by vabarbosa** [comment]
update available here: https://github.com/qiskit-community/qiskit-textbook/pull/1193

**Comment by y4izus** [comment]
This issue is approved and we are only waiting for having `textbook-beta` ready to be able to merge. So, I will close this issue and leave a [comment on the user story](https://github.com/Qiskit/qiskit.org/issues/1925#issue-932032451) to make easy to follow what we finished. We also have a reminder on the [Stabilize/prepare branch for merge issue](https://github.com/Qiskit/qiskit.org/issues/1934)
