### ISSUE TITLE
Investigate/review deployment process/steps required

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#1985]
- qiskit.org deploy action: https://github.com/Qiskit/qiskit.org/blob/main/.github/workflows/deploy.workflow.yml
- learn.qiskit.org deploy action: https://github.com/qiskit-community/platypus/blob/main/.github/workflows/release.yml

Related #1967

**Comment by techtolentino** [comment]
Hey @vabarbosa 

I'm posting my _findings_ for this investigation work, in the form of "documentation"; since this area, in general, is new material, it felt like the best way to summarize these findings, would be through a documentation-type format.

# Qiskit.org
(this could be added to the qiskit.org site wiki, under section [Dealing with Code](https://github.com/Qiskit/qiskit.org/wiki#dealing-with-code))

### Deployment

The qiskit.org application uses [GitHub Actions](https://docs.github.com/en/actions) to automate releases. This enables us to establish a Workflow and specify various steps that we need to include in our build process.

In the current configuration, the `build and deploy` Workflow is initiated by the following events:

- a manual trigger of the build
- a push to the `main` branch (merge)
- triggered automatically, as a part of a scheduled cron job


This `build and deploy` process includes the following steps:

- checks out project repo
- installs dependencies
- generates assets
- deploys to IBM Cloud Object Storage

It's important to note that the [`Deploy`](https://github.com/Qiskit/qiskit.org/blob/main/.github/workflows/deploy.workflow.yml#L41) step, which deploys the generated project assets to IBM Cloud Storage, is part of a larger process that involves other repositories as well. For security/privacy purposes, that _larger_ process is available in an internal, private repository [here](https://github.ibm.com/IBM-Q-Software/qiskit-community-mgt/tree/master/docs_deploy).

**TODO:**
// add testing (e.g., `Cypress run`) as a step, after dependencies are installed

___

# Textbook beta
(this could be added to the repository `wiki`, or, this can also reside within the `/docs` directory)

### Deployment

The Textbook beta application uses [GitHub Actions](https://docs.github.com/en/actions) to automate releases. This enables us to establish a Workflow and specify various steps that we need to include in our build process.

In the current configuration, the `Build and Release` Workflow is initiated by the following events:

- a manual trigger of the build
- a push to the `release` branch (merge)
- triggered automatically, as a part of a scheduled cron job


This `Build and Release` process includes the following steps:

- checks out project repo
- installs dependencies
- generates the build
- deploys to AppEngine

Details for the `Deploy to AppEngine` step can be found by visiting the GitHub Action page [here](https://github.com/google-github-actions/deploy-appengine).

**TODO**
// add testing (e.g., `Cypress run`) as a step, after dependencies are installed
// question: should appengine be replaced by IBM COS?

**Comment by vabarbosa** [comment]
@techtolentino this looks good. thank you! i would agree we should post these in the wiki for the appropriate repo (as part of https://github.com/Qiskit/qiskit.org/issues/1970). 

a couple thoughts:

- for textbook beta the AppEngine instance belongs to Mathigon 

- would it be worth documenting that the `secrets` used for deploying are coordinated with infrastructure team (for qiskit.org) and Mathigon (for textbook beta)
