### ISSUE TITLE
Quantum DB

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#2005]
Goals:
- Download problems and publish a scientific paper that demonstrates how their algorithm solves the problem in the DB.
- They can upload a solution to the DB and show how their method compares with the state-of-the-art solutions (already in the DB if it is successful).
- Cite the website as the reference for their scientific work
- To consult what are the best-in-class algorithms.

**Comment by lerongil** [comment]
User stories:

Quantum information researcher
Lurker 
Decision Maker 


1. A quantum information researcher can contribute problems from their research to the community, without duplicating prior efforts so that the community can see and contribute to all current problems. 

2. A quantum information researcher can contribute solutions from their research to the problems, without duplicating prior efforts, so that the community can compare novel results. 

3. A lurker can quickly find both the problems and solution so that they can compare and inform their own research. 

4. A decision maker can consume the material in a way that is at their level, without the help of domain experts in order to inform business decisions.

5. A quantum information research can cite the dashboard in order to provide proper credit to the solutions and problems used in their own research.
