### ISSUE TITLE
Mega menu not working correctly on mobile

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2097]
On android specifically, users can't use the mega menu. The page reloads before anything can be clicked.

This bug should be checked on iphones/ios devices as well.

The mega menu from the textbook home page works without issue This bug pertains to the mega menu on individual pages.

**Comment by techtolentino** [comment]
@JRussellHuffman 

Just doing a light follow up here:

- I tested the MegaMenu on iPhone, and for my device (11), it's working fine
- I also tested the MegaMenu on Android, via android studio (Pixel XL, Android 9 Pie), and it also seems to be working fine. Caveat: I had to use an Android simulator because I don't actually own an android device that has an up-to-date OS. I'm attaching the screen capture from the emulator, below... 



https://user-images.githubusercontent.com/6276074/166702335-76cc257c-7078-4f3b-bd48-2730ee99a166.mov

**Comment by techtolentino** [comment]
Checked w/ @JRussellHuffman and this seems to be resolved.

**Comment by JRussellHuffman** [comment]
Yep, I tested on android and it seems to be fine. Thanks Randy!
