### ISSUE TITLE
[General UI] Button active state

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2099]
Button active state stays active after clicking the navigating away. This state should only be used when mousing over or is active.

## Reproduce

- Go to [this page](https://qiskit.org/textbook-beta/course/introduction-course)
- click the primary CTA, which will open the next page in a new tab
- navigate back to other tab (still [this page](https://qiskit.org/textbook-beta/course/introduction-course))
- The button is in the active state without user input

Screenshot
<img width="339" alt="Screen Shot 2021-08-13 at 2 13 42 PM" src="https://user-images.githubusercontent.com/7633881/129407835-53d9c6ea-0299-4f15-9c45-0d22587ff922.png">

**Comment by eddybrando** [comment]
It's quite tricky at first, but I believe this is working properly.

We basically have 4 states here, which I coloured in the following video. The button states –and their colours– are:

- Default - Purple
- Hover - Red
- Active - Blue
- Focus - Green

When one changes back to the initial tab, the button's state is `focus`, which makes sense since it was the latest button to have been clicked.

In the following video, I click on the button first and then go back to the initial tab. There you can see the button being green. After that I navigate through some elements with the `tab` button.

https://user-images.githubusercontent.com/22047320/136684882-5e25d43f-251d-4723-baff-ebfc14b8ca1b.mov

While the button states are working as expected, we might consider creating multiple styles for the different button states.

**Comment by eddybrando** [comment]
That sounds like a good idea.

To following Carbon's pattern we could do:

- Default: Purple
- Hover: Darker purple
- Active: Even darker purple
- Focus: Inside border

Additionally, the arrow animation would only occur on `hover`, right? That would mean that when navigating with `tab`s, one wouldn't see the animation.

**Comment by eddybrando** [comment]
That's right. When tabbing, the button state would be `focus`.

As you mention, we would be missing the arrow animation but still have the border to visualise where the current focus is.

I'm also OK with the idea of only moving the arrow on `hover` then.

**Comment by y4izus** [comment]
This issue is no relevant anymore, so I close it
