### ISSUE TITLE
Additional event instrumentation to segment for Beta Textbook

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit.org#2139]
# Description

This would be a feature/ request, it's not a bug.

Need some events instrumented in segment for the Qiskit textbook for a few ongoing different analyses. 

# Stakeholders

These segment additions are primarily for analyzing the Code feature in the textbook, for Russell + team. But the translation pages would be for Yuri and team as they are looking to validate that they are prioritizing the right translations.

# Suggestions on Solutions

**High Priority Adds:**

- [ ] `Loaded a page` event for All pages in `Introduction to Quantum Computing` course: https://learn.qiskit.org/course/introduction/the-atoms-of-computation

     _*Currently the only way to track user path through the course is by `CTA clicked` this can be a bit limiting._

- [ ] Tracking for running and editing code. There is an open project to potentially alter this feature, and we are looking to collect data to analyze usage for this feature. This would include:
     `CTA Clicked` for `Run` button included in the Introduction course. This button is featured on the below pages:

- https://learn.qiskit.org/course/introduction/why-quantum-computing
- https://learn.qiskit.org/course/introduction/the-atoms-of-computation
- https://learn.qiskit.org/course/introduction/entangled-states
- https://learn.qiskit.org/course/introduction/visualizing-entanglement
- https://learn.qiskit.org/course/introduction/grovers-search-algorithm
- https://learn.qiskit.org/course/learning-qml/parametrized-quantum-circuits
- https://learn.qiskit.org/course/learning-qml/data-encoding
- https://learn.qiskit.org/course/learning-qml/quantum-feature-maps-and-kernels
- https://learn.qiskit.org/course/learning-qml/variational-classification

- [ ] Additionally would like to add an event which would tell us if the code has been altered for any of the CTAs above ^^ I think that the event `Performed Search` would work. And is there a way to store if the code ran properly after it was edited or if it was rejected? Similar to how the event for CTA clicked for the multiple choice questions has a property which tells if the question was answered correctly or incorrectly?

- [ ] CTA Clicked for different language translations for documentation: https://qiskit.org/documentation/index.html

- [ ] Loaded a page for the different language translations of the docs so that I can test if users are remaining on the page after they click in
https://qiskit.org/documentation/locale/ja_JP/index.html          
https://qiskit.org/documentation/locale/de_DE/index.html
https://qiskit.org/documentation/index.html
https://qiskit.org/documentation/locale/ko_KR/index.html
https://qiskit.org/documentation/locale/pt_BR/index.html
https://qiskit.org/documentation/locale/fr_FR/index.html
https://qiskit.org/documentation/locale/ta_IN/index.html

Medium/Low Priority:

Would like to expand the loaded a page event to show for all pages of the new textbook, like this page: https://learn.qiskit.org/course/ch-algorithms/quantum-fourier-transform

Would like to have `CTA clicked` for all pages of the new textbook (ie like this page: https://learn.qiskit.org/course/ch-algorithms/quantum-fourier-transform)

----

The medium/low priority is more a nice to have because I know that would be a lot to do! Let me know what feasible and how I can help! - Anne

**Comment by y4izus** [comment]
Hi @agebbie ! We will start working on this issue this sprint and I would like to organize the work effort here so we all could be aware of what's happening :).

@vabarbosa and I had a meeting yesterday and talked about this issue, so please Va, if I'm missing something, let me know

- [ ] **Loaded a page event for All pages in Introduction to Quantum Computing course**
Anne is trying to track how the user navigates through the Intro Course pages but she only see the `CTA Clicked` events. We have the [code for tracking this page navigation](https://github.com/qiskit-community/platypus/blob/main/frontend/textbook.ts#L64), but for some reason is not working. Since @techtolentino worked on set up this, Randy, could you take a look at this to figure out why it's not working?

- [ ] **Tracking for running and editing code.**
Anne, related with your concern about if adding tracking elements to the code block could reduce the performance, this should not happen. 
Since @eddybrando is the most familiar with the [Segment Schema](https://segment-standards.prod.ddp.cis.ibm.net/events), Eddy, could you work on finding the best event for tracking these code modifications in code blocks? also, could you work on tracking when the user clicks on the `run` button? Notice that for last one, you need to do more things because Thebe creates the `run` button, so you need to attach the segment info somehow (maybe with a listener or something similar)

- [ ] **CTA Clicked for different language translations for documentation**
We don't own the code under `qiskit.org/documentation`, so we cannot add segment without talking with someone on that team. @lerongil , do you know with whom should we talk?

- [ ] **Expand the loaded a page event to show for all pages of the new textbook**
@techtolentino , correct me if I'm wrong, but this should be done ones the first task is finished

- [ ] **Have CTA clicked for all pages of the new textbook**
@agebbie , could you give more info on this? I'm not sure about what do you need

- [ ] **Extra: tracking "order code lines" widget**
@agebbie , from here you need to know when the solution is correct or not, right? what is the priority for this?
<img width="500" alt="Captura de pantalla 2021-09-10 a las 12 56 45" src="https://user-images.githubusercontent.com/17231966/132843372-91a14c10-1f80-42ff-97bb-abdf062a2501.png">

**Comment by y4izus** [comment]
Hey @agebbie! we have already merge the code for tracking when code blocks run or are edited. We still have to work on the rest of the issues but this sprint we don't have time for them, sorry. We will try to continue next sprint, we let you know

**Comment by agebbie** [comment]
@eddybrando separated out the `cta clicked` portion to a new ticket like we discussed earlier this week, please find the new ticket [here](https://github.com/Qiskit/qiskit.org/issues/2188)

thanks!!

**Comment by eddybrando** [comment]
This can probably be closed, right @y4izus?

**Comment by y4izus** [comment]
Per offline conversations, we can close this issue
