### ISSUE TITLE
Use `lockfileVersion` 1 in `package-lock.json`

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2142]
In the `package.json` file we define in `engines` that the project works with the **node** version **14.x**.

According to https://nodejs.org/en/download/releases/, the latest **node** version that matches **14.x** (version **14.17.5**) corresponds to the **npm** version **6.14.14**.

For **npm** versions **5** and **6**, the lockfile version generated is `1`. (source: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion)

We're currently creating a lockfile version `2` which, whilst backwards compatible, is actually generated by the **npm** version 7.

Since per definition in the `package.json` engines configuration we should have the **npm** version **6** available in our environments, the lockfile version should be `1`.

This change would allow us commit `package-lock.json` updates consistently when generated from the **node** version we aim to support.

**Comment by jackoconnordev** [comment]
Hi guys, I've just started looking at qiskit.org and came across this "good first issue". I believe this issue is now stale and can be closed. 

Currently, in the main branch's `package.json` file, the `engines` option supports node 18 only . Node 18.0+ corresponds to npm version 8.6.0+, which uses package lock version 2.

Package-lock v2 introduced npm version 7: https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json?v=true
Node release npm version: https://nodejs.org/dist/index.json

**Comment by eddybrando** [comment]
Thank you very much @jackoconnordev! You're right. This issue can be closed now.
