### ISSUE TITLE
Investigate and fix broken branch deploy previews

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2395]
### Steps to reproduce the problem

1. Go to PR https://github.com/Qiskit/qiskit.org/pull/2392
2. Scroll down to the `Show Environments` section
4. See error `This branch had an error being deployed`

### What is the current behavior?

The build is created, but the Code Engine experiences a CE timeout

### What is the expected behavior?

When the build is created, CE can successfully create the preview

### Screenshots (optional but very helpful)
![Screen Shot 2022-01-04 at 8 01 41 AM](https://user-images.githubusercontent.com/6276074/148087503-3b67adf3-1e64-4eb1-adc2-2fac3305ded7.png)

![Screen Shot 2022-01-04 at 6 24 56 AM](https://user-images.githubusercontent.com/6276074/148080866-d00def4a-e220-4316-a0ad-b20a13228246.png)

**Comment by eddybrando** [comment]
This deployment error might also be related: https://github.com/Qiskit/qiskit.org/runs/4716248789?check_suite_focus=true#step:8:501

**Comment by Tansito** [comment]
The problem reported by @eddybrando was detected and being managed through #2399 .

About the problem reported in this issue is related with a timeout in code engine. It's an external application that we can't control at the end of the day so difficult to say a fix for this.

Related with CE too in #2397 we are adding a check to clean old images before rewrite them, something that we expect to improve the current errors in CE about the space and new docker images 🤞 .

**Comment by abdonrd** [comment]
Checking https://github.com/Qiskit/qiskit.org/pull/2392#issuecomment-1005228629... Maybe related with https://github.com/Qiskit/qiskit.org/discussions/2370?
