### ISSUE TITLE
As a learner beginning with an advanced undergraduate course, I want to learn the basic information of single systems, so that I have the foundation for multiple systems.

### ISSUE THREAD

**Issue by sderakhshandeh** [Qiskit/qiskit.org#2527]
### Background
Improve single systems lesson to provide learners with information regarding classical and quantum operations. 

### Goal
Release lesson 1 for single systems 

Acceptance Criteria: 

- [x]  Implement base level interactions including at least 2 MPC questions, 1 Autograder question.
- [x]  Implement custom interaction for unitary operations composer https://github.com/Qiskit/platypus/issues/1083
- [x]  Add math and vocab notations
- [x]  Include snippets of Qiskit code that coincide with the lessons
- [x]  User test the single systems page 
- [x]  Create slides and scripts for video lectures
- [x]  Consolidate existing material with new lecture to release first lesson as a "chapter"
- [x]  Record 1 lecture

**Comment by JRussellHuffman** [comment]
Adding a list of to-dos here that should be reviewed and prioritized
- [ ] new material should not open in new tabs
- [ ] the progress tracking line has disappeared
- [ ] progress tracking should track reading, instead of just interactions

**Comment by lerongil** [comment]
I think we decided to trim this one down to the first lecture only. My suggestion for a new title and acceptance criteria would be: 

As a learner beginning with an advanced undergraduate course, I want to learn the basis information of single systems, so that I have the foundation for future quantum computing knowledge.

- [ ] Implement base level interactions including at least 2 MPC questions, 1 Autograder question, and math notations. 
- [ ] Include snippets of Qiskit code that coincide with the lessons
- [ ] Create slides and scripts for video lectures 
- [ ] Consolidate existing material with new lecture to release first lesson as a "chapter" 
- [ ] Record 1 lecture

**Comment by lerongil** [comment]
@JRussellHuffman @jhwatrous Can we check off everything but record lectures here?

**Comment by lerongil** [comment]
Closing this out. User testing is ongoing.
