### ISSUE TITLE
Update Learn Page (Collection of issues & info)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2553]
As part of the Learn page refresh, we'll be adding new content cards and corresponding overview pages, for each Chapter, Course, and Tutorial.

This story is track updates for all the content (Card, Overview page, etc), and follow the [designs shown here](https://www.figma.com/file/X9p7omJAZncvDpg2IJLS6J/407-learn-page-migration?node-id=10%3A332):

- [x] https://github.com/Qiskit/qiskit.org/issues/2554
- [x] https://github.com/Qiskit/qiskit.org/issues/2555
- [x] https://github.com/Qiskit/qiskit.org/issues/2556
- [x] https://github.com/Qiskit/qiskit.org/issues/2557
- [x] https://github.com/Qiskit/qiskit.org/issues/2558
- [x] https://github.com/Qiskit/qiskit.org/issues/2559
- [x] https://github.com/Qiskit/qiskit.org/issues/2560
- [x] https://github.com/Qiskit/qiskit.org/issues/2561
- [x] https://github.com/Qiskit/qiskit.org/issues/2562
- [x] https://github.com/Qiskit/qiskit.org/issues/2591
- [x] https://github.com/Qiskit/qiskit.org/issues/2598
- [x] https://github.com/Qiskit/qiskit.org/issues/2599
- [x] https://github.com/Qiskit/qiskit.org/issues/2577
- [x] https://github.com/Qiskit/qiskit.org/issues/2580
- [x] https://github.com/Qiskit/web-components/issues/74
- [x] https://github.com/Qiskit/qiskit.org/issues/2616
- [x] #2605
- [ ] https://github.com/Qiskit/platypus/issues/1057
- [x] https://github.com/Qiskit/qiskit.org/issues/2624
- [ ] #2614

**Comment by vabarbosa** [comment]
not sure where to best capture this but wanted to bring it up for consideration sooner rather than later.

@frankharkins is updating and pulling in missing notebook from legacy textbook into the beta textbook:

- https://github.com/Qiskit/platypus/pull/967

as a result, a few of the courses will have some new chapters

- (see `toc.yaml` updates) https://github.com/Qiskit/platypus/pull/967/files#diff-5a735c42685f21683b95b7d53eedcfd821173d04ece65e4899709ab9470241db 

what this means is the overview page for these specific courses will need to be updated to take into account these new chapters.

depending on the timing we could release this update to learn content and have  be out of date almost immediately if not planned accordingly.

**Comment by techtolentino** [comment]
@vabarbosa - I was wondering how that large PR would impact this work... this is all good to know. Do you think Frank's PR will go in first?

That could help us identify which links need to be updated, and I'm down to help w/ that.
