### ISSUE TITLE
user is confused between community tab and section

### ISSUE THREAD

**Issue by CatherineKlauss** [Qiskit/qiskit.org#278]
user is confused by the difference between community tab and community section on qiskit.org

one solution is to remove community section from qiskit.org. The links to slack, medium, and youtube should be moved to the community tab webpage. the github link should be moved to the top of qiskit.org because it is vital to qiskit. The stack exchange link can be dropped because from feedback it is deemed to be not a place where poeple go, but a place that people find after googling a problem.

**Comment by lerongil** [comment]
I agree it seems redundant. Only caveat is that stack exchange is one area that some people from the team spend time looking at, so it should be maintained.

**Comment by marinaaisa** [comment]
Yesterday on the planning we suggested to fix this issue changing the copy of the Qiskit's section. Instead of "Qiskit community" we could tell "Qiskit social media" or something similar.
We would need the @CatherineKlauss 's help for this copy.
I'm going to add the "Needs copy" label to this issue.
<img width="1177" alt="Screen Shot 2019-11-05 at 12 03 39 PM" src="https://user-images.githubusercontent.com/8567677/68202603-52d6ea00-ffc4-11e9-809c-1554f9f5fd3c.png">
