### ISSUE TITLE
Vue 3 update: Fix other things that break because of the change 😬

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#2952]

**Comment by y4izus** [comment]
I've added the On-Hold label because this tasks should be the last one of the Bump Nuxt from 2 to 3

**Comment by techtolentino** [comment]
Just noting:

one thing that I noticed that broke, most likely because of the css grid, is the summer school event page Mosaic.

In this screenshot, only one tile shows up in the mosaic... 

Same thing is happening on the Seminar Series page (`/events/seminar-series`)

![Screenshot 2023-03-30 at 9 50 57 AM](https://user-images.githubusercontent.com/6276074/228909075-f0851c9e-f4bb-4f9c-9873-4f665be6ef4c.png)
