### ISSUE TITLE
As dev team we need to refactor breakpoints so we write better SCSS media queries

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#310]
As dev team we need to refactor breakpoints based on if we are "mobile first" or "desktop first" so we write better SCSS media queries. For this, we need to check analytics and understand if our users are mostly seeing our website from a mobile or from a desktop.
Then we need to refactor the media queries' breakpoints based on this.

**Comment by lerongil** [comment]
Desktop and mobile are about equivalent. Message me and we can talk about this more.

**Comment by delapuente** [comment]
To begin with, we should decide if we want it mobile-first or desktop-first. @y4izus asks to keep in mind not only our current audience but also the kind of audience we will want to reach in the mid-term.

**Comment by y4izus** [comment]
Now, the most visited pages are the landing page (it's in the [website project](https://github.com/Qiskit/qiskit.org)) and the documentation page (it's not in the [website project](https://github.com/Qiskit/qiskit.org)) and after seeing the qiskit website usability testing report it seems that it's because the user goes to the website to find how to install qiskit (and only the first time! then they go to github). 
We are going to create more pages (more experiments-projects, events, ...) that have no relation with the installation of qiskit and it's possible that the users changes the way they consume the web. We should have this in mind

**Comment by lerongil** [comment]
Implemented using Carbon's Small, Medium and Large.
