### ISSUE TITLE
[Advocates] design for QAMP showcasing projects

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3112]
Design task for how we'll showcase QAMP projects on the `/advocates` page

## Additional information
More info can be found in the original `user story` [here](https://github.com/Qiskit/qiskit.org/issues/3055)
Design file is located here: https://www.figma.com/file/V5leKM9L2op7GztvraV8rm/3112-Advocate-page---revisited?node-id=10%3A5817&t=Os73zFZZaKS4XDmN-1

**Comment by techtolentino** [comment]
@JRussellHuffman when you have a chance, can you share designs + a quick summary of what we discussed yesterday.

Thank you 🚀

**Comment by JRussellHuffman** [comment]
Design file is located here: https://www.figma.com/file/V5leKM9L2op7GztvraV8rm/3112-Advocate-page---revisited?node-id=10%3A5817&t=Os73zFZZaKS4XDmN-1

The design being proposed above does a few things
- adds a "status" filter to show active vs alumni members of the qiskit advocate program
- adds a new tab to show QAMP projects without drastically changing the structure of the page
- This also proposes to remove the "meet the advocates" text above the cards so that the page can be about both the QAMP projects and Advocates. 

Lastly, I know there have been discussions about the purple cards at the top. In the mockups here, all of those cards are still in place, but happy to discuss removing or changing them.

**Comment by techtolentino** [comment]
FYI @GemmaDawson ☝🏼

**Comment by techtolentino** [comment]
Can we close this issue, since the designs have been delivered?

Not sure if we're waiting for @GemmaDawson's approval?

**Comment by techtolentino** [comment]
This is done - the designs can be found in Figma
