### ISSUE TITLE
Bug: Ecosystem page overflow

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3120]
### Where does the issue happen?

https://qiskit.org/ecosystem

### What is the content issue?

Visit the Ecosystem page on mobile, and you'll see the responsiveness breaks due to the Tooltip component; turns out that on smaller screens, the Tooltip creates extra right-side spacing, leaving an empty gutter in the viewport.

### Screenshots

https://user-images.githubusercontent.com/6276074/231604495-10d609ac-26fc-42b0-9aab-e42ef7212bb8.mov

### Additional information

I also confirmed this bug in iOS | Chrome

**Comment by AanshSavla** [comment]
Can you please assign me this issue? I have just dig deep into carbon components files, node modules trying to find how we can reduce size of the tooltip. Found many place where there is a max-width. But still not able to find. I am currently working on it. Can you tell which node module was installed to use the '''<bx-tooltip-icon>''' tag. Bcoz there are 2 modules. carbon and carbon components.

**Comment by AanshSavla** [comment]
Can you please assign me this issue? I have just dig deep into carbon components files, node modules trying to find how we can reduce size of the tooltip. Found many place where there is a max-width. But still not able to find. I am currently working on it. Can you tell which node module was installed to use the <bx-tooltip-icon> tag. Bcoz there are 2 modules. carbon and carbon components.

**Comment by AanshSavla** [comment]
Can you please assign me this issue? I have just dig deep into carbon components files, node modules trying to find how we can reduce size of the tooltip. Found many place where there is a max-width. But still not able to find. I am currently working on it. Can you tell which node module was installed to use the '''bx-tooltip-icon''' tag. Bcoz there are 2 modules. carbon and carbon components.

**Comment by AanshSavla** [comment]
In components>Ui>UiCard.vue on line 45 there is a tag bx-tooltip-icon. On inspect tool I am able to change the max-width property but there is no file location mentioned there. Its telling as a constructed stylesheet. Probably it is connected to some stylesheet in the node modules. I tried making changes in different stylesheet in node modules but nothing was been reflected on the website. I think so we have to change the tag and use something else so that we can make style changes in the UiCard.vue file itself and no need to dig into the node module file.

**Comment by AanshSavla** [comment]
<img width="506" alt="Screenshot 2023-04-20 at 8 21 48 PM" src="https://user-images.githubusercontent.com/54212786/233404561-2d753b58-bf51-42b4-852a-9a83c681f720.png">
I changed the width in one of the CSS files inside node modules and got this result.

**Comment by techtolentino** [comment]
@AanshSavla - thanks for sharing this. It's true that _if_ we were allowed to customize the tooltip width, this would be a solution. However, with the way the Carbon components are built and exported, they don't allow us to _simply_ override the styles. Also, it's worth pointing out that going into the `node_modules` package and updating code, won't work as it isn't a common practice (unfortunately). 

We'll have to figure out another way to solve this, but I'm not sure what the solution is at the moment.

**Comment by AanshSavla** [comment]
I think so the way we use bx-tooltip must be changed. I temporarily tried implementing v-tooltip tag for vue but that also didnt work since it involves changes in other files. That is not reflecting in the website when I use it. We have to use a completely new way of implementing tooltip. Some tooltips have an auto direction so that the pop up changes according to view port. Lets see whether I can do it or not.

**Comment by techtolentino** [comment]
@javabster - for these tooltip definitions, I was wondering... are these only defined _within_ these tooltips, or can a user go to another page to find out what they mean?

**Comment by AanshSavla** [comment]
<img width="506" alt="Screenshot 2023-04-21 at 6 06 47 PM" src="https://user-images.githubusercontent.com/54212786/233637857-b33ccf85-fbaf-4709-a91a-1613948a8926.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54212786/233638270-bab6e11c-6f32-40c4-9fda-19bcadd24fee.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54212786/233638453-77f35c31-da74-46d2-a9eb-9025b22d5c2d.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/54212786/233638621-2abd8138-0b2f-4151-b9e2-60a8da7324c2.png">


I just increased the padding of the last component which contains the tooltip so that on IPhone screen that last component gets a new line and it is able to fit the content of tooltip within any screen.

**Comment by AanshSavla** [comment]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/54212786/233638900-f5df3db0-edaf-46ca-a2c0-a064835fad9c.png">
2nd image didn't show the tooltip. So reposting it.

**Comment by AanshSavla** [comment]
No need to change any node modules. Only a single line code change in UiCard.vue file.

**Comment by AanshSavla** [comment]
If this solution works then I will create a PR for this.

**Comment by techtolentino** [comment]
@AanshSavla - thanks for showing us this. Unfortunately, adding extra spacing within the tag breaks the design system rules that we follow from the [Carbon Design system](carbondesignsystem.com) 

Please hold off on this issue until we can get further direction, from either our content side or from design. Our team is thinking about what our options might be.

I also opened a new issue with the Carbon web-component project, to see if they'd consider exposing a way for us to override the styles of the tooltip. You can see that [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10365).

**Comment by AanshSavla** [comment]
Okay we will wait for their response.

**Comment by techtolentino** [comment]
@javabster your changes haven't been removed, but what's happened is that we upgraded to Nuxt 3, and with that upgrade, we're now using [Carbon Web Components](https://web-components.carbondesignsystem.com/?path=/story/components-tooltip--default), whereas before, we _were_ using Carbon Vue components. 

In Carbon Web components, the styles are encapsulated and protected by the shadow DOM... 

and I don't think there's a way to override (I could also just not know the proper technique to override these specific styles)

**Comment by y4izus** [comment]
This issue was fixed on https://github.com/Qiskit/qiskit.org/pull/3322, so I close it
