### ISSUE TITLE
Reorganize the landing page

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3125]
Once feat/providers is done (https://github.com/Qiskit/qiskit.org/pull/3044), some things on the landing page needs reorganization

- [x] Qiskit definition change
   **Done** in https://github.com/Qiskit/qiskit.org/pull/3142
- [x] Flip `Quick Start` order `What Can Qiskit Do` order.  Once https://github.com/Qiskit/qiskit.org/pull/3113 is merged, `What Can Qiskit Do` should go first. 
    **Done** in https://github.com/Qiskit/qiskit.org/pull/3141
- [x] Rename "Quick Start" to "Backends compatibility" or similar?
   **Done** [here](https://github.com/Qiskit/qiskit.org/pull/3044/commits/86aed859a7180eec22996a71d056a2b3482b458f)
- [ ] Some minor formatting issues:
  - [ ] Extend tabs in the "Quick Start"
  - [ ] Some form of code highlighting?

Based on @lerongil and @javabster feedback, among others.

I will create issues for them.

**Comment by JRussellHuffman** [comment]
Some feedback on the [preview here](https://qiskit-org-pr-3396.dcq4xc5i083.us-south.codeengine.appdomain.cloud/). And let me know if this feedback should be shared elsewhere.

- on larger screens, the hero image of the cryostat gets cropped at the bottom behind the "What Can Qiskit Do" section. I think it makes more sense to push that section down so that the image doesn't get cropped.
- on really small screens (below 320px width), the logo starts to get cropped on the right side. It should instead scale down.

Otherwise it looks good! Thanks for the solid implementation.

**Comment by techtolentino** [comment]
Just an FYI - we're still not able to extend the Tabs, since those styles are encapsulated by the Carbon web-component that we use; therefore, we're unable to override them for now.

**Comment by JRussellHuffman** [comment]
Which tabs are you referring to? Do you mean in the header? I think the header is good to go (in terms of ordering). I believe it was already correct in the preview link.

**Comment by techtolentino** [comment]
@JRussellHuffman - sorry, I was referring to the Quick Start Tabs…. 

there’s a checkbox in this issue description asking if we can extend the Tabs - if that’s referring to the width of the tabs, I don’t believe we can.

**Comment by 1ucian0** [comment]
As " Extend tabs in the "Quick Start" is not possible and "Some form of code highlighting?" can be an issue on its own. Closing as done.
