### ISSUE TITLE
[EventCard] limit description lengths 

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3206]
### Feature description

Currently, we allow cards to have a description by rendering content given in the `<slot>` outlet. 

However, sometimes the content can become really long; this not only throws off the layout from other cards, but it creates inconsistency.

We should figure out a way to limit the description passed into the event cards, either by limiting the content in the data, or figuring out some method of truncation.

### Screenshot

![Screenshot 2023-05-11 at 12 53 50 PM (2)](https://github.com/Qiskit/qiskit.org/assets/6276074/ac679e03-1dbe-4a62-a33c-b827ea409a33)

### Card content guidelines
[Figma board](https://www.figma.com/file/025EpGKBt27LQXuoFOhCp2/Qiskit-Card-content-guidelines?type=design&node-id=222-1591&mode=design&t=cLbspavCOv7fd3Mq-4)

### Additional context

This issue might occur on other card implementations as well, but it's most evident in event cards.

**Comment by tarunsamanta2k20** [comment]
@techtolentino is it looking good?

![image](https://github.com/Qiskit/qiskit.org/assets/55488549/bc0dd053-d927-4d03-bfe1-39f64c4da492)

**Comment by techtolentino** [comment]
Thank you for exploring this @tarunsamanta2k20. 

We're going to need to figure out how we'll address this... it might not be a CSS change, and it could be an effort of ensuring our descriptions have limits, in the DB... 

We'll come back to update this ticket once we come up w/ a consensus.

**Comment by paaragon** [comment]
The EventCard component takes the description from the <slot> given. That means it could possible receive something different from text.

I like the idea of truncating the description within the component since the description limit is something unique to the EventCard component but because it can receive anything besides just text, it shouldn’t.

I propose to change the component so that the description is another property instead of a child component
