### ISSUE TITLE
Find a better methodology for CSS so we stop having problems with scoping

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#326]

**Comment by y4izus** [comment]
Could you specify more about this issue? I've already fixed one problem about the scoping and I wanted to know if it's the same. I found that the scope in some component wasn't working because of the compilation of the selectors from something like `.a` to something like `.a[data-v-f3f3eg9]`. If we want to have styles for selectors that are child of `.a` we should use a `deep selector`. See this [explanation](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors).

For more information: 
- The issue I created (for the experiment page): #325 
- The [pull request with the solution](https://github.com/qiskit-community/community.qiskit.org/pull/119) to the problem

**Comment by marinaaisa** [comment]
Hey @y4izus, since @delapuente explained you about what I'm doing, I will guess that your question is already answered. Anyways, for anyone who wants to understand what this issue is about:
I'm searching for CSS methodologies/architectures to:
- Solve component encapsulation problem
- Minimize CSS size on production to improve our web performance
- Solve naming problem
- Only use variables based on a design system

**Comment by delapuente** [comment]
We solved the problem of scoping in #343, closing this in favour of testing new methodologies in #327
