### ISSUE TITLE
Bug: inconsistent colors on Ecosystem page (mobile)

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#3371]
### Steps to reproduce the problem

1. Using your phone, navigate to https://qiskit.org/ecosystem
2. Scroll down to the dropdown tabs and Filters
3. See inconsistencies

### What is the current behavior?

The colors for the Tiers Tabs and the Category Filters use Carbon "default" grays (pink arrows in screenshot below)

### What is the expected behavior?

To stay on brand, we should be using Carbon "cool" grays (blue arrows in screenshot below)

### Screenshots

![IMG_8917](https://github.com/Qiskit/qiskit.org/assets/6276074/aa6b4a19-bf03-405e-babf-38ac52f3ed7f)

**Comment by jackoconnordev** [comment]
## On topic

The default grey might actually be the right colour for Community and the real issue could be having Community appear in a dropdown box that looks like it should be an input with placeholder text, rather than what it really is which is the active tab header. (see tablet vs phone display).

### tablet

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/28d1e4ca-5137-4a4e-ab8c-01f85f46375a">

### phone

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/fe884db3-9fcb-47d7-bac9-e8c7474fb8d3">

## Off-topic

Should selected categories be visible in the Category dropdown after the dropdown is collapsed?

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/4722111d-ff46-4432-be42-01212af50f82">

<img width="905" alt="image" src="https://github.com/Qiskit/qiskit.org/assets/134723582/b5962aba-2671-4488-9cf1-992e3a753ff1">

**Comment by techtolentino** [comment]
This is something that we aren't able to fix ourselves, since the colors are encapsulated at the web-component level in Carbon. Closing for now.
