### ISSUE TITLE
Research what tests do we need

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3373]
We need to add more tests to our code, so this issue is for doing a research and decide what tests are we gonna use

**Acceptance criteria**
- [x] Decide what kind of tests are we gonna add
- [x] Create an issue for each test explaining why do we need it and tools to implement them
- [x] Add those issues to the [user story](https://github.com/Qiskit/qiskit.org/issues/3372)

**Comment by paaragon** [comment]
Issues created:

- https://github.com/Qiskit/qiskit.org/issues/3381
- https://github.com/Qiskit/qiskit.org/issues/3382
- https://github.com/Qiskit/qiskit.org/issues/3383

**Comment by paaragon** [comment]
I listed above three different types of tests.

I think the unit tests have to be done for components logic and hooks/utils. For the visual component test, I talked to @Eric-Arellano and he show me the playwritght E2E tests they use in qiskit documentation based on compare snapshots.

Also, @techtolentino talked to @abdonrd and they are using cypress as I proposed.

I think we should decide to use one of the two possibilities

**Comment by Eric-Arellano** [comment]
It's worth considering using Playwright for everything. It can handle unit tests and Cypress-style tests like interacting with the DOM and checking that interactivity works properly. It can be valuable to stick to one test runner because there are fewer interfaces to learn. We've had an excellent experience with Playwright so far. 

I've used Cypress before at a startup and it was okay, but we had lots of issues with flaky tests. Playwright intentionally tries to optimize to avoid flaky tests:

<img width="702" alt="Screenshot 2023-07-14 at 6 49 03 AM" src="https://github.com/Qiskit/qiskit.org/assets/14852634/5e86208a-9aed-4cd1-b80c-14514463236e">

And to recap our discussion, we went with Playwright rather than Jest/Jest Snapshots because I couldn't get Jest Snapshots to work with Docker, which is necessary for visual regression testing.

**Comment by abdonrd** [comment]
In Saiba we are using Vitest & Playwright, not Cypress.

**Comment by paaragon** [comment]
> In Saiba we are using Vitest & Playwright, not Cypress.

My bad then.. I understood other thing. Playwright should be the choice then!

**Comment by Eric-Arellano** [comment]
> Playwright should be the choice then!

Awesome! I recommend starting with 100% Playwright, and if you find it's deficient for e.g. unit tests, only then add another test runner like Vitest. Start as simple as possible.

**Comment by eddybrando** [comment]
Great job @paaragon, @Eric-Arellano and @abdonrd! Thank you all very much!
