### ISSUE TITLE
Double check Hotjar is working properly.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#356]
Support #292

**Comment by marinaaisa** [comment]
Qiskit.org's screenshots doesn't work because it's made with Polymer and as they say [here](https://help.hotjar.com/hc/en-us/articles/115012499507-Platforms-and-Frameworks-not-Compatible-with-Hotjar), Polymer uses Shadow DOM which it's not compatible with Hotjar.
This will be fixed when #258 is done since we will be using Nuxt.js instead of Polymer.

**Comment by delapuente** [comment]
What about now, @marinaaisa ? After merging #357 , is it now working?

**Comment by marinaaisa** [comment]
![Screen Shot 2019-12-30 at 11 58 43 AM](https://user-images.githubusercontent.com/8567677/71579209-cea06f00-2afb-11ea-90bb-6ffd8043f86b.png)

Yes, it works now!

**Comment by delapuente** [comment]
Thank you for checking. Closing.
