### ISSUE TITLE
Some links in the footer are broken during development time

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#391]
### Steps to reproduce the problem
This is not happening in production, only while developing.

1. Clone the repository and make `npm install` inside.
2. Launch a dev server, running `npm run dev`.
3. Scroll down until the footer.
4. Click on "Become an Advocate" link.

### What is the current behavior?
The link is broken.
![broken-footer-link](https://user-images.githubusercontent.com/757942/72076711-48074100-32f6-11ea-8726-bf3b681e69c3.gif)

### What is the expected behavior?
The link takes you to the advocate page.

**Comment by y4izus** [comment]
The problem is that the vue-router is looking for the `el` before the new page is rendered. It only happens with the links to a `id`:
- `/advocates#become-an-advocate`
- `/experiments#browse-the-experiments`
If we open the link in a new tab or if we use `<a>` instead of `<nuxt-link>` it works in development time, but I don't think that these two are a good solution, what do you think @delapuente @marinaaisa ?

**Comment by delapuente** [comment]
Thank you @y4izus for pointing in the right direction!

Fixing this bug, I've discovered this other one in production #411
