### ISSUE TITLE
Investigate alternatives to Zeit Now

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#403]

**Comment by y4izus** [comment]
We are looking for a tool that allow us to auto deploy the pull request in order to see a working demo of the fix. I find two possible alternatives to zeit, [surge](https://surge.sh/) and [seed](https://seed.run):
- ***surge***:
  - Can be use with *Travis* and *Github*
  - The entire setup is free if the project is open source
  - ONLY for static websites
  - We can define for free a subdomain to deploy the static website
- ***seed***:
  - Built specifically for Serverless apps with multiple services
  - Don't need to set up a CI/CD pipeline but it can work with it
  - Only free for a single user account

References: 
- [Travis(Surge, Github) => Auto Deploy Every PR, Branch and Tag](https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f)
- [Auto Deployment of Pull Requests on GitHub using Surge Technology](https://www.codementor.io/@harshit98/auto-deployment-of-pull-requests-on-github-using-surge-technology-g9ixkvbu4)
- [Seed => Working with PR](https://seed.run/docs/working-with-pull-requests.html)
- [Seed => Connect your own CI](https://seed.run/docs/connect-your-own-ci)
