### ISSUE TITLE
Come up with the first designs for filtering events.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#404]
Support #300

**Comment by marinaaisa** [comment]
## Proposals
### [Proposal 1](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=30%3A20&viewport=-657%2C1580%2C0.31718358397483826&scaling=min-zoom):
It's based on https://developer.ibm.com/events/ and https://www.uipath.com/events . **This is the closest proposal to IBM and Carbon design**.

### Proposal 2:
It uses [Multi-Select component](http://vue.carbondesignsystem.com/?path=/story/components-cvmultiselect--default) from Carbon in a horizontal way.

"Proposal 2" has 4 different variations concerning the events section:
- [Straight lines - Even items](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A2835&viewport=747%2C614%2C0.25&scaling=min-zoom)
- [Straight lines - Mixed items](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A5958&viewport=747%2C614%2C0.25&scaling=min-zoom)
- [Perpendicular lines - Even items](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A2852&viewport=747%2C614%2C0.25&scaling=min-zoom)
- [Perpendicular lines - Mixed items](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A2869&viewport=747%2C614%2C0.25&scaling=min-zoom)

### [Proposal 3](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A6394&viewport=705%2C467%2C0.5801852941513062&scaling=min-zoom):

It uses [Multi-Select component](http://vue.carbondesignsystem.com/?path=/story/components-cvmultiselect--default) from Carbon in a vertical way.

## Favorite choice:
- [Proposal 2 - Straight lines - Mixed items](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-events?node-id=96%3A5958&viewport=747%2C614%2C0.25&scaling=min-zoom)

**Comment by JRussellHuffman** [comment]
In general I think it looks nice, clean, and polished

The filters are clearly visible to the user, but don’t look mandatory. If there are only a few events, the filters are clearly optional

Visually, it strikes nice balance as a useful page (as opposed to purely marketing) but also something enjoyable to look at

**Some feedback:**

Is there an empty state?

Is there a mobile state?

Is there a state when there is only 1 or 2 upcoming events?

Should there be a section to add an event, request an event, etc.?

What types of events are show?
- Can “pending” events be included (ie events that are still being organized)?
- Are small scale community events included, such as university hosted hackathons?
- can users add their own events? Or request to have an event added

What happens when they click on event?
- Is there anything between this page and the individual event page? 
- make sure the jump between the two pages is feels seemly

Do we need to explain what each event type is (eg camp, unconference, etc)?


I like the hero video, but I’m a little mixed about it.
- should that format be used consistently on other pages?
- is it something that we hope to be adopted elsewhere?
- how much will it affect load time?
- I think the page totally functions and would be a good page without it, but its a nice visual element
- personally I think you should do something more like what is done on the Qiskit Camp Africa page


The tiled layout version, with the differing card widths, is fun, but it is probably easiest for users as a list, and we don’t want the utility of the page to get lost.

I don’t think we need the text “discover all events related to qiskit” that is currently at the top.

regarding visual layout,  red vertical columns in the template should line up with the text, not the container
- the container should go past, either by 8 pixels or 16 pixels
- The gutters a little wide, and I believe IQX uses a gutter of 8 pixels, if you wanted to reference that.

**Comment by delapuente** [comment]
I consider this reviewerd by the events team and so, the first iteration is over.

**Comment by marinaaisa** [comment]
Answering @JRussellHuffman 's feedback:

> Is there an empty state?

There wasn't but I've designed it [here](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-Events-index?node-id=271%3A3043&viewport=-919%2C3365%2C0.5&scaling=min-zoom) using Carbon's notification component.

> Is there a mobile state?

Yes, there are actually 2 different proposals, both are interactive prototypes, let me know which one you prefer, I like more the second one:
- [First proposal](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-Events-index?node-id=234%3A3205&viewport=-919%2C3365%2C0.5&scaling=min-zoom)

- [Second proposal](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-Events-index?node-id=273%3A3340&viewport=-919%2C3365%2C0.5&scaling=min-zoom)

> Is there a state when there is only 1 or 2 upcoming events?

This is the [proposal](https://www.figma.com/proto/GKMCqzcq7li1ZVi2OZtn0m/Qiskit-Events-index?node-id=30%3A20&viewport=-208%2C1279%2C0.25&scaling=min-zoom) we are going to work with so it's prepared for 1 or 2 events as you mention.

> Should there be a section to add an event, request an event, etc.?

So far we don't have this requirement. Maybe in the future.

> What types of events are show?
> Can “pending” events be included (ie events that are still being organized)?
> Are small scale community events included, such as university hosted hackathons?
> Can users add their own events? Or request to have an event added
> Do we need to explain what each event type is (eg camp, unconference, etc)?

The events team should answer these questions.

> What happens when they click on event?

We will link each event to its individual page in case of having it.

> Is there anything between this page and the individual event page? Make sure the jump between the two pages feels seamless.

You are right, that something we should work in the next iteration. At least the header should be the same.

> I like the hero video, but I’m a little mixed about it.
> should that format be used consistently on other pages?
> is it something that we hope to be adopted elsewhere?

I don't know, I liked the fact of showing a dynamic video only in this page to break the layout but it's true that maybe we should add a header on it that it's the same used for individual event pages. It feels a bit disconnected.

> how much will it affect load time?

It doesn't affect load time at all because we can do it totally asynchronous for desktop and not to load on mobile devices.

> I think the page totally functions and would be a good page without it, but its a nice visual element. Personally I think you should do something more like what is done on the Qiskit Camp Africa page.

This is something we can do on a next iteration just because creating an interactive map is more difficult and it will take a longer time for the development team. Creating a list page as we are doing here is just faster for now. But I agree.


> The tiled layout version, with the differing card widths, is fun, but it is probably easiest for users as a list, and we don’t want the utility of the page to get lost.

The list is what we are going to do for the first iteration.

> I don’t think we need the text “discover all events related to qiskit” that is currently at the top.

Okay, I removed it.

> Regarding visual layout, red vertical columns in the template should line up with the text, not the container.
> The container should go past, either by 8 pixels or 16 pixels

I don't fully understand it, could you send me an example of it, please?

> The gutters a little wide, and I believe IQX uses a gutter of 8 pixels, if you wanted to reference that.

https://developer.ibm.com/events/ 's gutter between events is 16px, in this design is 32px. Do you think I should change this?
