### ISSUE TITLE
Aer example gives deprecation warning

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#449]
### Steps to reproduce the problem

See: https://github.com/Qiskit/qiskit/issues/820

**Comment by delapuente** [comment]
### Steps to reproduce the problem

1. Install the latest version of Qiskit
2. Navigate to qiskit.org/aer
3. Try the snippet with the latest version of Qiskit

### What is the current behavior?

The code launches a deprecation warning:
> DeprecationWarning: This function is been deprecated and moved to a method of the`NoiseModel` class. For equivalent functionality use `NoiseModel.from_backend(properties, **kwargs).
  DeprecationWarning)

### What is the expected behavior?

No deprecation warning is shown.
