### ISSUE TITLE
Add animation of the CTA icon

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#609]
Human Design presented an animation of the CTA where the arrow moved when hover. Could be a good addition to recover it from oblivion and implement it.

**Comment by korgan00** [comment]
Im in.

**Comment by JRussellHuffman** [comment]
Prototype of a few different options here: https://www.figma.com/proto/FRGCly4lcursxfAShIEBEn/609-Animation-prototyping?node-id=29%3A24&viewport=686%2C376%2C1.0708061456680298&scaling=min-zoom

Note that the variations between the options are speed of transition, and direction of transition. I'm most partial to "Option 1". Figma can specify transition options that correspond to CSS transition properties. I chose "ease out" for all the options because I like the idea of the animation starting fast and then slowing down, but could certainly be persuaded otherwise.
