### ISSUE TITLE
Extract AppLink with the logo to its own component

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#681]
In the menu, the AppLink with the logo is used a couple of times.

Extracting it to its own component would also allow us to customize the internal colour if combined with #661

**Comment by delapuente** [comment]
Dup of #682

**Comment by y4izus** [comment]
I think this is not done. On #682 we have created a component for the logo (just the svg), but this issue is related to create a component that includes the `AppLink` and the `AppLogo` in the same component and this is not done.

If you agree (@delapuente , @techtolentino , @korgan00 ), we should reopen the issue
