### ISSUE TITLE
Research menu scrolling

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#788]
Investigate alternatives for implementing the _sticky_ index.

**Comment by y4izus** [comment]
There are different options to implement the _sticky_ table of contents:

- `position: sticky`, a native CSS feature. On [MDN](https://developer.mozilla.org/es/docs/Web/CSS/position) we can see the compatibility with different browsers:
<img width="1015" alt="Screen Shot 2020-08-05 at 11 59 13" src="https://user-images.githubusercontent.com/17231966/89399694-1848dc00-d713-11ea-83a0-426e3ec5fbea.png">

- Fake that behavior with JavaScript. You measure scroll positions and flip-flop the element between position: relative (or static or anything else) and position: fixed as needed. By doing the flip-flopping yourself, there may be jumpiness when these elements go from fixed position to not. This issue is worsened in mobile device browsers.

- Use libraries/plugins: To see browser support we need to look at these plugins/libraries one by one. For example:
  - [Stickybits](https://github.com/yowainwright/stickybits) a lightweight (~2KB) alternative. It is an easy to set up plugin that is cross-compatible with any other plugins, libraries, or frameworks. This will work for browsers that support [.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) whether position: sticky is supported or not. Browser support for `.classList`:
  <img width="1017" alt="Screen Shot 2020-08-05 at 12 16 20" src="https://user-images.githubusercontent.com/17231966/89401368-7c6c9f80-d715-11ea-9637-a0b1fce5c275.png">
  - [`sticky-js`](https://github.com/rgalus/sticky-js): Same compatibilities as `stickybits`

To have in mind when making the decision: Looking at Amplitude, we can see that only 0.48% of the users use IE as browser

I decided to use the CSS option because it is easy to implement, we don't have to include more JS and we have more browser compatibility
