### ISSUE TITLE
Overview page jump/refresh when selecting tabs on accordion 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#853]
### Steps to reproduce the problem

Use Google chrome to open overview page and select different tabs in the accordion

### What is the current behavior?

It refreshes/jumps when selecting different tabs. 

### What is the expected behavior?

You remain in the same position on the screen when selecting the different tabs

**Comment by delapuente** [comment]
This is caused by [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring). From MDN:

> Scroll anchoring adjusts the scroll position to compensate for the changes outside of the viewport. This means that the point in the document the user is looking at remains in the viewport, which may mean their scroll position actually changes in terms of how far they have moved through the document.

It seems the procedure for determining the anchor is different in Firefox, Safari and Chrome and Chrome ends up anchoring the header of the accordion item, so, in order to preserve it at the same position inside the browser viewport, it scrolls all the content down.

We can control which HTML elements can be used as anchors with the [CSS property `overflow-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor). Excluding the accordion items is enough to solve it.

Done in 58043c34f82c16db7abf7e59aec22a85883a27eb
