### ISSUE TITLE
make a page about the providers

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#87]
@ajavadia can you add your ideas here.

**Comment by carlosazaustre** [comment]
Any design or copywritting for it?

**Comment by lerongil** [comment]
I think a page about the providers is important since contributors are able to add their own providers. I like the idea of having a page on the community tab for 3rd-party providers which should include copy for how to contribute your own provider. 

That being said, the details for the IBMQ Provider/job/backends might be a better fit for the Qiskit documentation.

Assuming @ajavadia is good with this, I can draft up some copy/images for the providers page in the community tab and post them here.

**Comment by ajavadia** [comment]
Hi @lerongil, yes if you could design something for this that would be great. I mainly wanted the qiskit.org page to also show something about device access through the IBMQProvider, since that is an important thing for qiskit users which is not covered in terra, aqua, ignis, aer.

So I was thinking of creating a tab with some information, mainly pulled from these tutorials:

https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/basics/the_ibmq_provider.ipynb

https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/backend_monitoring_tools.ipynb

https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/creating_a_provider.ipynb
