### ISSUE TITLE
Update header on Qiskit Hackathon Global Site

### ISSUE THREAD

**Issue by justjosie** [Qiskit/qiskit.org#870]
![Website_Banner_1920x1080](https://user-images.githubusercontent.com/57451534/91209019-b572b100-e6d0-11ea-8314-ee828bb28072.png)

Website URL: qiskit.org/events/qiskit-hackathon-global

**Comment by delapuente** [comment]
Removing the `Decoration` tag since it is intended for marking the tasks we need to do during our decoration sprint starting on Monday 7th.

**Comment by delapuente** [comment]
@justjosie the header of the event pages already include the name of the event and the dates. You can use the tagline to specify the hashtag too. Using this background will repeat the information. Removing all the texts and leaving the header only would reduce the accessibility of the site, possibly its position in search engines since part of the important information is in a picture format.
