### ISSUE TITLE
Remove the tutorial link

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit.org#88]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/15731369/52907411-1f361300-322f-11e9-9414-afd56ff7cf25.png">

Can we remove the tutorial link in all elements? I think that it is not clear that these all link to the tutorials.

**Comment by pistoia** [comment]
I agree.  Since the tutorials are all unified now, it does not make sense for each element to have its own link.  Perhaps we can remove the *Tutorials* button from each element's page, and have a common link at the top, next to *Documentation* and *Tools", like in the following figure:
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/11150011/52909381-a7c7aa00-3255-11e9-82fd-9e3702644ce2.png">

**Comment by jaygambetta** [comment]
I am good with this. If it get too busy i would also make the elements one and then have a way of viewing them with a landing page or something. 

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/15731369/52914834-272b9c80-329b-11e9-813d-e5b63bb3b0bf.png">
